### ISSUE TITLE
Issue with running run_wire_cutting.py

### ISSUE THREAD

**Issue by Stefanos19** [personalrobotics/ada_assistance_policy#1]
I get the error:
```Traceback (most recent call last):
  File "/home/snikolai/old_ada_meal_scenario_ws/src/ada_wire_cutting/scripts/run_wire_cutting.py", line 11, in <module>
    from ada_wire_cutting.actions.wire_cutting import WireCutting
  File "/home/snikolai/old_ada_meal_scenario_ws/src/ada_wire_cutting/src/ada_wire_cutting/actions/wire_cutting.py", line 3, in <module>
    from align_gripper import AlignGripper
  File "/home/snikolai/old_ada_meal_scenario_ws/src/ada_wire_cutting/src/ada_wire_cutting/actions/align_gripper.py", line 3, in <module>
    from assistance_policy_action import AssistancePolicyAction
  File "/home/snikolai/old_ada_meal_scenario_ws/src/ada_wire_cutting/src/ada_wire_cutting/actions/assistance_policy_action.py", line 3, in <module>
    from ada_assistance_policy.AdaHandler import AdaHandler
  File "/home/snikolai/old_ada_meal_scenario_ws/src/ada_assistance_policy/src/ada_assistance_policy/AdaHandler.py", line 7, in <module>
    from DataRecordingUtils import TrajectoryData
  File "/home/snikolai/old_ada_meal_scenario_ws/src/ada_assistance_policy/src/ada_assistance_policy/DataRecordingUtils.py", line 15, in <module>
    file_directory = rospkg.RosPack().get_path('ada_assistance_policy') + '/trajectory_data'
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 200, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: ada_assistance_policy```

**Comment by sjavdani** [comment]
Are you sure you have this library checked out, and in your ros package path? It looks like rospkg can't find it.
